name: "Action Test"

on:
  push:
    branches:
      - "main"
      - "release/v1"
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Test MySQL Container Action"
        uses: "ej-shafran/container-action@v1"
        id: "setup-container"
        with:
          docker-options: "-e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=testtest -p 3306:3306"
          image: "mysql:latest"
          name: "test"

      - name: "Check that database exists"
        run: "ps -ef | grep mysql"

      - name: "Check the output"
        run: "echo ${{ steps.setup-container.outputs.container-id }}"
