name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Test MySQL Container Action"
        uses: "ej-shafran/container-action@v0.0.2"
        with:
          docker-options: "-e MYSQL_DATABASE=test -e MYSQL_ROOT_PASSWORD=testtest -p 3306:3306"
          image: "mysql:latest"
          name: "test"

      - name: "Check that database exists"
        run: "ps -ef | grep mysql"
